apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-zozo-setting
spec:
  forms:
    - group: basic
      label: 基础设置
      formSchema:
        - $formkit: text
          name: sub_title
          label: 二级标题
          value: Opposite is endless darkness
        - $formkit: text
          name: footer_slogan
          label: 页脚标语
          value: 我的精神家园
        - $formkit: radio
          name: mathjax
          label: MathJax 公式渲染
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: radio
          name: disqus
          id: disqus
          label: Disqus 评论系统
          value: true
          options:
            - label: 启用
              value: true
            - label: 停用
              value: false
        - $formkit: text
          if: "$get(disqus).value"
          name: disqus_shortname
          id: disqus_shortname
          label: Disqus site shortname
          help: disqus.com创建站点的唯一shortname

    - group: sns
      label: 社交资料
      formSchema:
        - $formkit: text
          name: github
          label: Github
        - $formkit: text
          name: twitter
          label: Twitter
        - $formkit: text
          name: facebook
          label: Facebook
        - $formkit: text
          name: weibo
          label: Weibo
        - $formkit: text
          name: instagram
          label: Instagram
        - $formkit: text
          name: steam
          label: Steam
        - $formkit: text
          name: zhihu
          label: Zhihu
        - $formkit: text
          name: telegram
          label: Telegram
        - $formkit: text
          name: playstation
          label: PlayStation
          help: "示例：https://psnprofiles.com/AKmoex"

          
