apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-zozo
spec:
  displayName: Theme ZOZO
  author:
    name: AKmoex (原作者 varkai > https://github.com/varkai/hugo-theme-zozo)
    website: "https://blog.akmoex.com"
  description: Theme ZOZO 移植自 hugo-theme-zozo, 参考halo-theme-zozo
  logo: "https://halo.run/logo"
  website: "https://zozo-demo.akmoex.com"
  repo: "https://github.com/AKmoex/theme-zozo"
  settingName: "theme-zozo-setting"
  configMapName: "theme-zozo-configMap"
  version: "1.0.0"
  require: "2.0.0"
